#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置 
---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  type-aliases-package: com.zz.soft.entities # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml # mapper映射文件

spring:
  profiles: dev # 开发环境
  application:
    name: microservice-product #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver  # mysql驱动包
    url: jdbc:mysql://106.12.156.112:3306/springcloud_db01?characterEncoding=UTF-8 # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5 # 数据库连接池的最小维持连接数
      initial-size: 5 # 初始化连接数
      max-total: 5 # 最大连接数
      max-wait-millis: 150 # 等待连接获取的最大超时时间
#    initialization-mode: always  #需要加上这句，否则不会自动执行sql文件
#    schema: classpath:${spring.profiles.active:dev}/schema.sql
#    data: classpath:${spring.profiles.active:dev}/data.sql
#  profiles:
#    active: dev # dev/sit/prod等。分别对应开发、测试、生产等不同运行环境。

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      #单机版本的注册
      #defaultZone: http://localhost:6001/eureka
      #集群版Eureka服务注册
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
  instance:  #指定实例ID,就不会显示主机名了
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true
---
server:
  port: 8003

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  type-aliases-package: com.zz.soft.entities # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml # mapper映射文件

spring:
  profiles: prod # 生产环境
  application:
    name: microservice-product-bus #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver  # mysql驱动包
    url: jdbc:mysql://106.12.156.112:3306/springcloud_db01?characterEncoding=UTF-8 # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5 # 数据库连接池的最小维持连接数
      initial-size: 5 # 初始化连接数
      max-total: 5 # 最大连接数
      max-wait-millis: 150 # 等待连接获取的最大超时时间
#    initialization-mode: always  #需要加上这句，否则不会自动执行sql文件
#    schema: classpath:${spring.profiles.active:dev}/schema.sql
#    data: classpath:${spring.profiles.active:dev}/data.sql
#  profiles:
#    active: dev # dev/sit/prod等。分别对应开发、测试、生产等不同运行环境。

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      #单机版本的注册
      #defaultZone: http://localhost:6001/eureka
      #集群版Eureka服务注册
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
  instance:  #指定实例ID,就不会显示主机名了
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true
